replication_factor = 3

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
rpc_secret = "4425f5c26c5e11581d3223904324dcb5b5d5dfb14e5e7f35e38c595424f5f1e6"
rpc_bind_addr = "[::]:3901"
api_key = "garage-access-key"
api_secret = "garage-secret-key"

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"